module_name: "VCU"


buckets:
    bucket_1:
        id: 1
        frequency_hz: 50
        parameters:
            - vcu_apps2
            - vcu_brake_pressure_front
            
    bucket_2:
        id: 2
        frequency_hz: 10
        parameters:
            - inv_temp_igbt_a
            - inv_temp_igbt_b
            - inv_temp_igbt_c
            - inv_temp_gate_driver
            - inv_temp_ctrl_board
            - inv_temp_rtd_1
            - inv_temp_rtd_2
            - inv_temp_rtd_3
            - inv_temp_rtd_4
            - inv_temp_rtd_5
            - inv_motor_temp
            - inv_torque_shudder
            - inv_digital_in_1
            - inv_digital_in_2
            - inv_digital_in_3
            - inv_digital_in_4
            - inv_digital_in_5
            - inv_digital_in_6
            - inv_digital_in_7
            - inv_digital_in_8
            - inv_motor_angle
            - inv_motor_speed
            - inv_motor_ac_freq
            - inv_delta_resolver_filtered
            - inv_current_phase_a
            - inv_current_phase_b
            - inv_current_phase_c
            - inv_current_dc_bus
            - inv_dc_bus_voltage
            - inv_peak_output_voltage
            - inv_vd_voltage
            - inv_vq_voltage
            - inv_flux_cmd
            - inv_flux_feedback
            - inv_id_feedback
            - inv_iq_feedback
            - inv_1v5_ref
            - inv_2v5_ref
            - inv_5v_ref
            - inv_12v_ref
            - inv_post_fault_lo
            - inv_post_fault_hi
            - inv_run_fault_lo
            - inv_run_fault_hi
            - inv_torque_cmd
            - inv_torque_feedback
            - inv_power_on_timer
            - inv_modulation_index
            - inv_flux_weakening
            - inv_id_cmd
            - inv_iq_cmd
            - inv_torque_cmd_high
            - inv_torque_feedback_high
            - inv_motor_speed_high
            - inv_dc_bus_voltage_high
            - inv_vsm_state
            - inv_pwm_freq
            - inv_inverter_state
            - inv_relay_state
            - inv_states_byte4
            - inv_states_byte5
            - inv_states_byte6
            - inv_states_byte7

parameters_produced:
# ADC1:
    vcu_apps2:
        produced_by: ADC1_IN10
        sensor:
            name: "linear_pos_sensor_25"
            output: voltage
        num_samples_buffered: 1

    vcu_brake_pressure_front:
        produced_by: ADC1_IN11
        sensor:
            name: "brake_pressure_sensor"
            output: voltage
        num_samples_buffered: 1

# inverter parameters
    inv_temp_igbt_a:
        produced_by: CAN
        sensor:
            name: "cascadia_inverter"
            output: temp_igbt_a
        num_samples_buffered: 1
        
    inv_temp_igbt_b:
        produced_by: CAN
        sensor:
            name: "cascadia_inverter"
            output: temp_igbt_b
        num_samples_buffered: 1
        
    inv_temp_igbt_c:
        produced_by: CAN
        sensor:
            name: "cascadia_inverter"
            output: temp_igbt_c
        num_samples_buffered: 1
        
    inv_temp_gate_driver:
        produced_by: CAN
        sensor:
            name: "cascadia_inverter"
            output: temp_gate_driver
        num_samples_buffered: 1
        
    inv_temp_ctrl_board:
        produced_by: CAN
        sensor:
            name: "cascadia_inverter"
            output: temp_ctrl_board
        num_samples_buffered: 1
        
    inv_temp_rtd_1:
        produced_by: CAN
        sensor:
            name: "cascadia_inverter"
            output: temp_rtd_1
        num_samples_buffered: 1
        
    inv_temp_rtd_2:
        produced_by: CAN
        sensor:
            name: "cascadia_inverter"
            output: temp_rtd_2
        num_samples_buffered: 1
        
    inv_temp_rtd_3:
        produced_by: CAN
        sensor:
            name: "cascadia_inverter"
            output: temp_rtd_3
        num_samples_buffered: 1
        
    inv_temp_rtd_4:
        produced_by: CAN
        sensor:
            name: "cascadia_inverter"
            output: temp_rtd_4
        num_samples_buffered: 1
        
    inv_temp_rtd_5:
        produced_by: CAN
        sensor:
            name: "cascadia_inverter"
            output: temp_rtd_5
        num_samples_buffered: 1
        
    inv_motor_temp:
        produced_by: CAN
        sensor:
            name: "cascadia_inverter"
            output: motor_temp
        num_samples_buffered: 1
        
    inv_torque_shudder:
        produced_by: CAN
        sensor:
            name: "cascadia_inverter"
            output: torque_shudder
        num_samples_buffered: 1
        
    inv_digital_in_1:
        produced_by: CAN
        sensor:
            name: "cascadia_inverter"
            output: digital_in_1
        num_samples_buffered: 1
        
    inv_digital_in_2:
        produced_by: CAN
        sensor:
            name: "cascadia_inverter"
            output: digital_in_2
        num_samples_buffered: 1
        
    inv_digital_in_3:
        produced_by: CAN
        sensor:
            name: "cascadia_inverter"
            output: digital_in_3
        num_samples_buffered: 1
        
    inv_digital_in_4:
        produced_by: CAN
        sensor:
            name: "cascadia_inverter"
            output: digital_in_4
        num_samples_buffered: 1
        
    inv_digital_in_5:
        produced_by: CAN
        sensor:
            name: "cascadia_inverter"
            output: digital_in_5
        num_samples_buffered: 1
        
    inv_digital_in_6:
        produced_by: CAN
        sensor:
            name: "cascadia_inverter"
            output: digital_in_6
        num_samples_buffered: 1
        
    inv_digital_in_7:
        produced_by: CAN
        sensor:
            name: "cascadia_inverter"
            output: digital_in_7
        num_samples_buffered: 1
        
    inv_digital_in_8:
        produced_by: CAN
        sensor:
            name: "cascadia_inverter"
            output: digital_in_8
        num_samples_buffered: 1
        
    inv_motor_angle:
        produced_by: CAN
        sensor:
            name: "cascadia_inverter"
            output: motor_angle
        num_samples_buffered: 1
        
    inv_motor_speed:
        produced_by: CAN
        sensor:
            name: "cascadia_inverter"
            output: motor_speed
        num_samples_buffered: 1
        
    inv_motor_ac_freq:
        produced_by: CAN
        sensor:
            name: "cascadia_inverter"
            output: motor_ac_freq
        num_samples_buffered: 1
        
    inv_delta_resolver_filtered:
        produced_by: CAN
        sensor:
            name: "cascadia_inverter"
            output: delta_resolver_filtered
        num_samples_buffered: 1
        
    inv_current_phase_a:
        produced_by: CAN
        sensor:
            name: "cascadia_inverter"
            output: current_phase_a
        num_samples_buffered: 1
        
    inv_current_phase_b:
        produced_by: CAN
        sensor:
            name: "cascadia_inverter"
            output: current_phase_b
        num_samples_buffered: 1
        
    inv_current_phase_c:
        produced_by: CAN
        sensor:
            name: "cascadia_inverter"
            output: current_phase_c
        num_samples_buffered: 1
        
    inv_current_dc_bus:
        produced_by: CAN
        sensor:
            name: "cascadia_inverter"
            output: current_dc_bus
        num_samples_buffered: 1
        
    inv_dc_bus_voltage:
        produced_by: CAN
        sensor:
            name: "cascadia_inverter"
            output: dc_bus_voltage
        num_samples_buffered: 1
        
    inv_peak_output_voltage:
        produced_by: CAN
        sensor:
            name: "cascadia_inverter"
            output: peak_output_voltage
        num_samples_buffered: 1
        
    inv_vd_voltage:
        produced_by: CAN
        sensor:
            name: "cascadia_inverter"
            output: vd_voltage
        num_samples_buffered: 1
        
    inv_vq_voltage:
        produced_by: CAN
        sensor:
            name: "cascadia_inverter"
            output: vq_voltage
        num_samples_buffered: 1
        
    inv_flux_cmd:
        produced_by: CAN
        sensor:
            name: "cascadia_inverter"
            output: flux_cmd
        num_samples_buffered: 1
        
    inv_flux_feedback:
        produced_by: CAN
        sensor:
            name: "cascadia_inverter"
            output: flux_feedback
        num_samples_buffered: 1
        
    inv_id_feedback:
        produced_by: CAN
        sensor:
            name: "cascadia_inverter"
            output: id_feedback
        num_samples_buffered: 1
        
    inv_iq_feedback:
        produced_by: CAN
        sensor:
            name: "cascadia_inverter"
            output: iq_feedback
        num_samples_buffered: 1
        
    inv_1v5_ref:
        produced_by: CAN
        sensor:
            name: "cascadia_inverter"
            output: 1v5_ref
        num_samples_buffered: 1
        
    inv_2v5_ref:
        produced_by: CAN
        sensor:
            name: "cascadia_inverter"
            output: 2v5_ref
        num_samples_buffered: 1
        
    inv_5v_ref:
        produced_by: CAN
        sensor:
            name: "cascadia_inverter"
            output: 5v_ref
        num_samples_buffered: 1
        
    inv_12v_ref:
        produced_by: CAN
        sensor:
            name: "cascadia_inverter"
            output: 12v_ref
        num_samples_buffered: 1
        
    inv_post_fault_lo:
        produced_by: CAN
        sensor:
            name: "cascadia_inverter"
            output: post_fault_lo
        num_samples_buffered: 1
        
    inv_post_fault_hi:
        produced_by: CAN
        sensor:
            name: "cascadia_inverter"
            output: post_fault_hi
        num_samples_buffered: 1
        
    inv_run_fault_lo:
        produced_by: CAN
        sensor:
            name: "cascadia_inverter"
            output: run_fault_lo
        num_samples_buffered: 1
        
    inv_run_fault_hi:
        produced_by: CAN
        sensor:
            name: "cascadia_inverter"
            output: run_fault_hi
        num_samples_buffered: 1
        
    inv_torque_cmd:
        produced_by: CAN
        sensor:
            name: "cascadia_inverter"
            output: torque_cmd
        num_samples_buffered: 1
        
    inv_torque_feedback:
        produced_by: CAN
        sensor:
            name: "cascadia_inverter"
            output: torque_feedback
        num_samples_buffered: 1
        
    inv_power_on_timer:
        produced_by: CAN
        sensor:
            name: "cascadia_inverter"
            output: power_on_timer
        num_samples_buffered: 1
        
    inv_modulation_index:
        produced_by: CAN
        sensor:
            name: "cascadia_inverter"
            output: modulation_index
        num_samples_buffered: 1
        
    inv_flux_weakening:
        produced_by: CAN
        sensor:
            name: "cascadia_inverter"
            output: flux_weakening
        num_samples_buffered: 1
        
    inv_id_cmd:
        produced_by: CAN
        sensor:
            name: "cascadia_inverter"
            output: id_cmd
        num_samples_buffered: 1
        
    inv_iq_cmd:
        produced_by: CAN
        sensor:
            name: "cascadia_inverter"
            output: iq_cmd
        num_samples_buffered: 1
        
    inv_torque_cmd_high:
        produced_by: CAN
        sensor:
            name: "cascadia_inverter"
            output: torque_cmd_high
        num_samples_buffered: 1
        
    inv_torque_feedback_high:
        produced_by: CAN
        sensor:
            name: "cascadia_inverter"
            output: torque_feedback_high
        num_samples_buffered: 1
        
    inv_motor_speed_high:
        produced_by: CAN
        sensor:
            name: "cascadia_inverter"
            output: motor_speed_high
        num_samples_buffered: 1
        
    inv_dc_bus_voltage_high:
        produced_by: CAN
        sensor:
            name: "cascadia_inverter"
            output: dc_bus_voltage_high
        num_samples_buffered: 1
        
    inv_vsm_state:
        produced_by: CAN
        sensor:
            name: "cascadia_inverter"
            output: vsm_state
        num_samples_buffered: 1
        
    inv_pwm_freq:
        produced_by: CAN
        sensor:
            name: "cascadia_inverter"
            output: pwm_freq
        num_samples_buffered: 1
        
    inv_inverter_state:
        produced_by: CAN
        sensor:
            name: "cascadia_inverter"
            output: inverter_state
        num_samples_buffered: 1
        
    inv_relay_state:
        produced_by: CAN
        sensor:
            name: "cascadia_inverter"
            output: relay_state
        num_samples_buffered: 1
        
    inv_states_byte4:
        produced_by: CAN
        sensor:
            name: "cascadia_inverter"
            output: states_byte4
        num_samples_buffered: 1
        
    inv_states_byte5:
        produced_by: CAN
        sensor:
            name: "cascadia_inverter"
            output: states_byte5
        num_samples_buffered: 1

    inv_states_byte6:
        produced_by: CAN
        sensor:
            name: "cascadia_inverter"
            output: states_byte6
        num_samples_buffered: 1
        
    inv_states_byte7:
        produced_by: CAN
        sensor:
            name: "cascadia_inverter"
            output: states_byte7
        num_samples_buffered: 1
        
